name: build

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: set up go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
        id: go

      - name: checkout
        uses: actions/checkout@v2

      - name: build and test
        run: |
          make all

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
